export const DIAL_CODES = [
{ "code": "AF", "name": "Afghanistan", "dial_code": "+93" },
{ "code": "AL", "name": "Albania", "dial_code": "+355" },
{ "code": "DZ", "name": "Algeria", "dial_code": "+213" },
{ "code": "AS", "name": "American Samoa", "dial_code": "+1" },
{ "code": "AD", "name": "Andorra", "dial_code": "+376" },
{ "code": "AO", "name": "Angola", "dial_code": "+244" },
{ "code": "AI", "name": "Anguilla", "dial_code": "+1" },
{ "code": "AG", "name": "Antigua and Barbuda", "dial_code": "+1" },
{ "code": "AR", "name": "Argentina", "dial_code": "+54" },
{ "code": "AM", "name": "Armenia", "dial_code": "+374" },
{ "code": "AW", "name": "Aruba", "dial_code": "+297" },
{ "code": "AU", "name": "Australia", "dial_code": "+61" },
{ "code": "AT", "name": "Austria", "dial_code": "+43" },
{ "code": "AZ", "name": "Azerbaijan", "dial_code": "+994" },
{ "code": "BS", "name": "Bahamas", "dial_code": "+1" },
{ "code": "BH", "name": "Bahrain", "dial_code": "+973" },
{ "code": "BD", "name": "Bangladesh", "dial_code": "+880" },
{ "code": "BB", "name": "Barbados", "dial_code": "+1" },
{ "code": "BY", "name": "Belarus", "dial_code": "+375" },
{ "code": "BE", "name": "Belgium", "dial_code": "+32" },
{ "code": "BZ", "name": "Belize", "dial_code": "+501" },
{ "code": "BJ", "name": "Benin", "dial_code": "+229" },
{ "code": "BM", "name": "Bermuda", "dial_code": "+1" },
{ "code": "BT", "name": "Bhutan", "dial_code": "+975" },
{ "code": "BO", "name": "Bolivia", "dial_code": "+591" },
{ "code": "BA", "name": "Bosnia and Herzegovina", "dial_code": "+387" },
{ "code": "BW", "name": "Botswana", "dial_code": "+267" },
{ "code": "BR", "name": "Brazil", "dial_code": "+55" },
{ "code": "BN", "name": "Brunei", "dial_code": "+673" },
{ "code": "BG", "name": "Bulgaria", "dial_code": "+359" },
{ "code": "BF", "name": "Burkina Faso", "dial_code": "+226" },
{ "code": "BI", "name": "Burundi", "dial_code": "+257" },
{ "code": "KH", "name": "Cambodia", "dial_code": "+855" },
{ "code": "CM", "name": "Cameroon", "dial_code": "+237" },
{ "code": "CA", "name": "Canada", "dial_code": "+1" },
{ "code": "CV", "name": "Cape Verde", "dial_code": "+238" },
{ "code": "KY", "name": "Cayman Islands", "dial_code": "+1" },
{ "code": "CF", "name": "Central African Republic", "dial_code": "+236" },
{ "code": "TD", "name": "Chad", "dial_code": "+235" },
{ "code": "CL", "name": "Chile", "dial_code": "+56" },
{ "code": "CN", "name": "China", "dial_code": "+86" },
{ "code": "CO", "name": "Colombia", "dial_code": "+57" },
{ "code": "KM", "name": "Comoros", "dial_code": "+269" },
{ "code": "CG", "name": "Congo", "dial_code": "+242" },
{ "code": "CD", "name": "Congo (DRC)", "dial_code": "+243" },
{ "code": "CR", "name": "Costa Rica", "dial_code": "+506" },
{ "code": "HR", "name": "Croatia", "dial_code": "+385" },
{ "code": "CU", "name": "Cuba", "dial_code": "+53" },
{ "code": "CY", "name": "Cyprus", "dial_code": "+357" },
{ "code": "CZ", "name": "Czech Republic", "dial_code": "+420" },
{ "code": "DK", "name": "Denmark", "dial_code": "+45" },
{ "code": "DJ", "name": "Djibouti", "dial_code": "+253" },
{ "code": "DM", "name": "Dominica", "dial_code": "+1" },
{ "code": "DO", "name": "Dominican Republic", "dial_code": "+1" },
{ "code": "EC", "name": "Ecuador", "dial_code": "+593" },
{ "code": "EG", "name": "Egypt", "dial_code": "+20" },
{ "code": "SV", "name": "El Salvador", "dial_code": "+503" },
{ "code": "EE", "name": "Estonia", "dial_code": "+372" },
{ "code": "ET", "name": "Ethiopia", "dial_code": "+251" },
{ "code": "FI", "name": "Finland", "dial_code": "+358" },
{ "code": "FR", "name": "France", "dial_code": "+33" },
{ "code": "GE", "name": "Georgia", "dial_code": "+995" },
{ "code": "DE", "name": "Germany", "dial_code": "+49" },
{ "code": "GH", "name": "Ghana", "dial_code": "+233" },
{ "code": "GI", "name": "Gibraltar", "dial_code": "+350" },
{ "code": "GR", "name": "Greece", "dial_code": "+30" },
{ "code": "GL", "name": "Greenland", "dial_code": "+299" },
{ "code": "GT", "name": "Guatemala", "dial_code": "+502" },
{ "code": "HT", "name": "Haiti", "dial_code": "+509" },
{ "code": "HN", "name": "Honduras", "dial_code": "+504" },
{ "code": "HK", "name": "Hong Kong", "dial_code": "+852" },
{ "code": "HU", "name": "Hungary", "dial_code": "+36" },
{ "code": "IS", "name": "Iceland", "dial_code": "+354" },
{ "code": "IN", "name": "India", "dial_code": "+91" },
{ "code": "ID", "name": "Indonesia", "dial_code": "+62" },
{ "code": "IR", "name": "Iran", "dial_code": "+98" },
{ "code": "IQ", "name": "Iraq", "dial_code": "+964" },
{ "code": "IE", "name": "Ireland", "dial_code": "+353" },
{ "code": "IL", "name": "Israel", "dial_code": "+972" },
{ "code": "IT", "name": "Italy", "dial_code": "+39" },
{ "code": "JM", "name": "Jamaica", "dial_code": "+1" },
{ "code": "JP", "name": "Japan", "dial_code": "+81" },
{ "code": "JO", "name": "Jordan", "dial_code": "+962" },
{ "code": "KZ", "name": "Kazakhstan", "dial_code": "+7" },
{ "code": "KE", "name": "Kenya", "dial_code": "+254" },
{ "code": "KR", "name": "South Korea", "dial_code": "+82" },
{ "code": "KW", "name": "Kuwait", "dial_code": "+965" },
{ "code": "KG", "name": "Kyrgyzstan", "dial_code": "+996" },
{ "code": "LV", "name": "Latvia", "dial_code": "+371" },
{ "code": "LB", "name": "Lebanon", "dial_code": "+961" },
{ "code": "LT", "name": "Lithuania", "dial_code": "+370" },
{ "code": "LU", "name": "Luxembourg", "dial_code": "+352" },
{ "code": "MY", "name": "Malaysia", "dial_code": "+60" },
{ "code": "MX", "name": "Mexico", "dial_code": "+52" },
{ "code": "NL", "name": "Netherlands", "dial_code": "+31" },
{ "code": "NZ", "name": "New Zealand", "dial_code": "+64" },
{ "code": "NG", "name": "Nigeria", "dial_code": "+234" },
{ "code": "NO", "name": "Norway", "dial_code": "+47" },
{ "code": "PK", "name": "Pakistan", "dial_code": "+92" },
{ "code": "PE", "name": "Peru", "dial_code": "+51" },
{ "code": "PH", "name": "Philippines", "dial_code": "+63" },
{ "code": "PL", "name": "Poland", "dial_code": "+48" },
{ "code": "PT", "name": "Portugal", "dial_code": "+351" },
{ "code": "QA", "name": "Qatar", "dial_code": "+974" },
{ "code": "RO", "name": "Romania", "dial_code": "+40" },
{ "code": "RU", "name": "Russia", "dial_code": "+7" },
{ "code": "SA", "name": "Saudi Arabia", "dial_code": "+966" },
{ "code": "RS", "name": "Serbia", "dial_code": "+381" },
{ "code": "SG", "name": "Singapore", "dial_code": "+65" },
{ "code": "SK", "name": "Slovakia", "dial_code": "+421" },
{ "code": "SI", "name": "Slovenia", "dial_code": "+386" },
{ "code": "ZA", "name": "South Africa", "dial_code": "+27" },
{ "code": "ES", "name": "Spain", "dial_code": "+34" },
{ "code": "SE", "name": "Sweden", "dial_code": "+46" },
{ "code": "CH", "name": "Switzerland", "dial_code": "+41" },
{ "code": "TH", "name": "Thailand", "dial_code": "+66" },
{ "code": "TR", "name": "Turkey", "dial_code": "+90" },
{ "code": "UA", "name": "Ukraine", "dial_code": "+380" },
{ "code": "AE", "name": "UAE", "dial_code": "+971" },
{ "code": "GB", "name": "United Kingdom", "dial_code": "+44" },
{ "code": "US", "name": "United States", "dial_code": "+1" },
{ "code": "UZ", "name": "Uzbekistan", "dial_code": "+998" },
{ "code": "VN", "name": "Vietnam", "dial_code": "+84" }
]