import { IFinPartner } from "./partners.model";

export const FIN_PARTNERS: IFinPartner[] = [
  {
    "UID": "0e15268f8b0b11efa836c87f5454cc3a",
    "INN": null,
    "KPP": null,
    "checking_account": null,
    "name": "Поставщик 2",
    "status": 0,
    "user_shop_id": 586,
    "description": null,
    "shop_name": "Все",
    "expenses_item": null,
    "income_item": null,
    "sum_partners": "0.00",
    "sum_receipt": null,
    "sum_order": null,
    "count_operation": null
  },
  {
    "UID": "f302eba0824111efa836c87f5454cc3a",
    "INN": null,
    "KPP": null,
    "checking_account": null,
    "name": "Поставщик",
    "status": 0,
    "user_shop_id": 586,
    "description": null,
    "shop_name": "Все",
    "expenses_item": null,
    "income_item": null,
    "sum_partners": "0.00",
    "sum_receipt": null,
    "sum_order": null,
    "count_operation": null
  },
  {
    "UID": "ab8fd2d22ee311ef907dc87f5454cc3a",
    "INN": null,
    "KPP": null,
    "checking_account": null,
    "name": "test1232",
    "status": 0,
    "user_shop_id": 399,
    "description": "опа",
    "shop_name": "Все",
    "expenses_item": null,
    "income_item": null,
    "sum_partners": "0.00",
    "sum_receipt": null,
    "sum_order": null,
    "count_operation": null
  },
  {
    "UID": "045ce2c42ecf11ef907dc87f5454cc3a",
    "INN": null,
    "KPP": null,
    "checking_account": null,
    "name": "Kontragent",
    "status": 0,
    "user_shop_id": 399,
    "description": null,
    "shop_name": "Все",
    "expenses_item": null,
    "income_item": null,
    "sum_partners": "0.00",
    "sum_receipt": null,
    "sum_order": null,
    "count_operation": null
  },
  {
    "UID": "fdf4706c2d6a11ef907dc87f5454cc3a",
    "INN": null,
    "KPP": null,
    "checking_account": null,
    "name": "Вымпелком",
    "status": 0,
    "user_shop_id": 399,
    "description": null,
    "shop_name": "Все",
    "expenses_item": null,
    "income_item": null,
    "sum_partners": "0.00",
    "sum_receipt": null,
    "sum_order": null,
    "count_operation": null
  },
  {
    "UID": "a976f0c5299811ef907dc87f5454cc3a",
    "INN": null,
    "KPP": null,
    "checking_account": null,
    "name": "Контрагенты тест",
    "status": 0,
    "user_shop_id": 399,
    "description": null,
    "shop_name": "Все",
    "expenses_item": null,
    "income_item": null,
    "sum_partners": "0.00",
    "sum_receipt": null,
    "sum_order": null,
    "count_operation": null
  },
  {
    "UID": "fbb09679da3b11ee965bc87f5454cc3a",
    "INN": null,
    "KPP": null,
    "checking_account": null,
    "name": "Тест 42",
    "status": 0,
    "user_shop_id": 399,
    "description": null,
    "shop_name": "Все",
    "expenses_item": null,
    "income_item": null,
    "sum_partners": "0.00",
    "sum_receipt": null,
    "sum_order": null,
    "count_operation": null
  }
]