export interface IAbcGridData {
  data: IAbcGridDataItem[],
  otherDeductions: {
    "title": string,
    "subfields": unknown[],
    "totalCount": null | number,
    "totalSum": number,
    "diffInPercents": null | number,
    "description": string
  },
  total: {
    "sales": number,
    "orders": number,
    "orders_sum": number,
    "sales_from_orders": number,
    "sales_count": number,
    "profit": number,
    "sebes": number,
    "logistic": number,
    "commission": number,
    "acquiring": number,
    "adv": number,
    "other_deductions": number,
    "total_stocks": number,
    "avg_orders_day": number,
    "hranenie": number
  },
  totalRecord: number
}

export interface IAbcGridDataItem {
  "nmID": string,
  "size": string,
  "brand": string | null,
  "category_pnl": string,
  "subject": string | null,
  "kkey": string,
  "techSize_count": string,
  "object": string | null,
  "photo_new": string | null,
  "sku": string,
  "seller_price": number,
  "sales": number,
  "percent_sales": number,
  "orders": string,
  "orders_sum": number,
  "sales_from_orders": string,
  "sales_from_orders_sum": number,
  "sales_count": string,
  "percent_sales_redeemed": string | number | null,
  "percent_sales_delivered": string | number | null,
  "profit": number,
  "percent_profit": number,
  "profitability": string| number,
  "nalog_nds": number,
  "sebes": number,
  "sebes_percent": string | number | null,
  "unit_cost_price_per": string | number | null,
  "cost_price": string | number | null,
  "sebes_other_deductions": string | number | null,
  "cost_price_percent": number,
  "sebes_other_deductions_percent": number,
  "hranenie": number,
  "logistic": number,
  "commission": number,
  "acquiring": number,
  "adv": string,
  "adv_external": string,
  "marketing": string,
  "other_deductions": number,
  "platnaya_priyomka": number,
  "platnaya_priyomka_count": string,
  "turnover": string | number | null,
  "wuo_30_days_percent_sales_delivered": string | number | null,
  "turnover_sales": string | number | null,
  "avg_orders_day": number,
  "total_stocks": string,
  "abc": string,
  "drr": number,
  "drr_sales": number,
  "percent_sales_sort": number,
  "percent_profit_sort": number,
  "turnover_sort": number,
  "unit_avg_sale_sum": number,
  "other_deductions_unit_rub": number,
  "marketing_unit_rub": number,
  "adv_unit_rub": number,
  "adv_external_unit_rub": number,
  "acquiring_unit_rub": number,
  "logistic_unit_rub": number,
  "logistic_unit_per": number,
  "commission_unit_rub": number,
  "commission_unit_per": number,
  "hranenie_unit_rub": number,
  "hranenie_unit_percent": number,
  "platnaya_priyomka_unit_rub": number,
  "platnaya_priyomka_unit_percent": number,
  "unit_profit_per": number,
  "unit_percent_profit": number,
  "unit_percent_cost_price_per": number,
  "total_costs_unit_rub": number,
  "total_costs_unit_per": number
}